# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Mybatis-Plus
subtitle: "A enhanced toolkit of Mybatis to simplify the operation of CURD."
description: "A enhanced toolkit of Mybatis to simplify the operation of CURD."
author: baomidou
language: zh-cn
timezone: PRC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mp.baomidou.com
root: /
permalink: news/:year/:month/:day/:title/

# Directory
archive_dir: news
code_dir: downloads/code

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: baomidou

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
      github: git@github.com:baomidou/mybatis-plus-doc.git,gh-pages
      coding: git@git.coding.net:yangyang0507/mybatis-plus-doc.git,coding-pages

# Third-Party Plugins
duoshuo_shortname: mp-doc
google_analytics: UA-85414008-1
baidu_analytics: efbacb2342e8f494c196a4eb9ad00dfc
algolia:
  api_key: 922162742d707e8db20520e0c7e6fd98
  index_name: mybatis-plus
github: baomidou/mybatis-plus
