name: Build Doc

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build docs
        run: yarn run build
      - name: Deploy docs
        uses: AnonyStar/git-push@v2
        env:
          GITHUB_EMAIL: "koyangslash@gmail.com"
          GITHUB_USERNAME: "D.Yang"
          PUBLISH_REPO: https://${{ secrets.CODING_USER }}:${{ secrets.CODING_TOKEN }}@e.coding.net/yangyang0507/mybatis-plus-doc.git
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./docs
